### ISSUE TITLE
How to resolve Could not install from "node_modules/jsdoc-template" ?

### ISSUE THREAD

**Issue by oshliaer** [classroomtechtools/ObjectStore#2]
```sh
$> npm i
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/jsdoc-template" as it does not contain a package.json file.
```

This may not be a bug but we cannot install the environment without all the links and references. 

_Just an opinion_. Perhaps JSDoc generation can exist as a standalone script or as a subproject for documentation in general.

**Comment by brainysmurf** [comment]
Yeah, it really should be a submodule. The workaround is to just delete it from the dev dependencies for the moment. You don't need it, as you won't need to regenerate the documentation.

I'll come up with a real solution and commit.

**Comment by oshliaer** [comment]
Yes, I did that. Thanks.
